### ISSUE TITLE
search-bar doesn't work properly on mobile

### ISSUE THREAD

**Issue by jonathanpauluze-n1** [vtex-apps/search#122]
When the `search-bar` block is declared inside a `header-layout` block, the search bar doesn't work properly on mobile.

![https://i.imgur.com/PDlNpot.png](https://i.imgur.com/PDlNpot.png)

But if we declare the `search-bar` block directly in `header` and `header.full` it works as expected.

![https://i.imgur.com/z4H3RRb.gif](https://i.imgur.com/z4H3RRb.gif)

This workaround doesn't work for us because we need to declare `search-bar` inside a layout component to set component position and styles.

### Error example
Given the following code:
```jsonc
{
  "header": {
    "blocks": ["header-layout.mobile"]
  },

  "header.full": {
    "blocks": ["header-layout.mobile"]
  },

  "header-layout.mobile": {
    "children": ["sticky-layout#header-row-mobile"]
  },

  "sticky-layout#header-row-mobile": {
    "children": ["flex-layout.row#header-row-mobile"]
  },

  "flex-layout.row#header-row-mobile": {
    "children": [
      "drawer",
      "logo",
      "minicart.v2"
    ],
    "props": {
      "fullWidth": true
    }
  },
}
```

The expected behavior on mobile is:
- render a button
- when the button is clicked, show the search input.

The actual behavior is:
- render the search input as in desktop

But if we make a few changes in code, it'll work properly, but there's blocks that we can't declare inside `header` and `header.full`, such as `drawer` and `flex-layout`.
```jsonc
{
  "header": {
    "blocks": ["search-bar"]
  },

  "header.full": {
    "blocks": ["search-bar"]
  }
}
```

**Comment by klzns** [comment]
There are two header components:

1. legacy once, that uses search-bar as a block
2. current one, which uses header-layout blocks

The legacy one is the one that is giving Search bar this behavior on mobile:
https://github.com/vtex-apps/store-header/blob/3b4dda953ecb32c495b5ec44847e34e802023656/react/legacy/components/FixedContent.js#L55

Search Bar for itself doesn't have this feature.

My recommendation is to create a React component that have this logic of the legacy header to toggle the visibility of search-bar.

Example:

`interfaces.json`
```json
{
  "search-mobile": {
    "component": "SearchMobile",
    "composition": "children"
  }
}
```

`blocks.json`
```json
{
  "search-mobile": {
    "children": [
      "search-bar"
    ]
  }
}
```

`react/SearchMobile.tsx`
```tsx
import React, { useState } from 'react'
import { ButtonWithIcon } from 'vtex.styleguide'
import { IconSearch, IconClose } from 'vtex.store-icons'
import { useRuntime } from 'vtex.render-runtime'

function SearchMobile({ children }) {
  const { deviceInfo } = useRuntime()
  const [isVisible, setVisible] = useState(false)

  if (deviceInfo.isMobile === false) {
    return null
  }

  if (!isVisible) {
    return (
      <div>
        <ButtonWithIcon
          icon={
            <span>
              <IconSearch />
            </span>
          }
          variation="tertiary"
          onClick={() => setVisible(true)}
        />
      </div>
    );
  }

  return (
    <div>
      {children}
      <div>
        <ButtonWithIcon
          icon={
            <span>
              <IconClose />
            </span>
          }
          variation="tertiary"
          onClick={() => setVisible(true)}
        />
      </div>
    </div>
  );
}

export default SearchMobile
```
