### ISSUE TITLE
Q&A: O Componente de Search (VTEX Intelligence Search)

### ISSUE THREAD

**Issue by zeluizr** [vtex-apps/search#124]
Ele pode ser usado fora do Header?

Por ejemplo, eu gostaria de usar ele no HERO da home, e claro que no header de outras páginas.
Porém na home, queria usar ele no HERO,isso é possivel?

Muito obrigado!

**Comment by chrsmutti** [comment]
Olá @zeluizr, tudo certo? Consegue adicionar um pouco mais de informação a sua pergunta?

- Qual componente do search você está referenciando?
- Qual componente é o Hero que você referenciou?
- Algumas imagens para acompanhar ajudariam!

O componente `autocomplete-result-list.v2` acompanha o componente de `search-bar`, que pode ser inserido em qualquer bloco, portanto, se for sobre ele, sim, ele poderia ser colocado em qualquer bloco que compõe a home page, e dependendo da página, aparecer em outros blocos, mas o componente que vai ser movido de lugar é o `search-bar`.
