### ISSUE TITLE
Autocomplete show more link redirect bug

### ISSUE THREAD

**Issue by sebaskun98** [vtex-apps/search#63]
**Describe the bug**
Show more link is not getting the parent URL and is redirecting to another website.
**To Reproduce**
Go to https://shop.samsung.com/br/, search `galaxy` and wait for the autocomplete be filled.
Hover the show more link and you'll see that the query is wrong and is not having the /br/ in the URL neither.
**Expected behavior**
Correct query and /br/ before the query.
**Video**
https://www.loom.com/share/863979ad51e54d1b99100de5bac083b0
**Additional context**
https://github.com/vtex-apps
vtex.search: 1.x

**Comment by chrsmutti** [comment]
@sebaskun98 Thanks for the report! We'll look into it.

cc @vtex-apps/search-engagement-team

**Comment by hiagolcm** [comment]
@sebaskun98 Thanks for the report.

Solved in https://github.com/vtex-apps/search/pull/64
