### ISSUE TITLE
vtex.search-resolver not updating sellingPriceWithTax in category

### ISSUE THREAD

**Issue by doruradu** [vtex-apps/search#80]
Hi!

The search resolver is not updating the correct prices as defined in the site-editor. Shelf, Search & Product page are ok, only the category is not displaying the right prices.

Demo to see the bug: https://golive--dacris.myvtex.com/articole-de-birou/organizare-si-arhivare/bibliorafturi

**Comment by chrsmutti** [comment]
Hi @doruradu! 

At the moment the resolver `@1.x` only returns tax information when using the `__unstableProductOriginVtex` prop, I noticed that on `store.search` (used on the full text search) this prop is being used, but it's not declared on the block `store.search#category`.

You can set that prop in all `store.search`  blocks present in that store-theme. We’re working on a more permanent fix that doesn’t involve changes to the store-theme’s blocks, sorry for the inconvenience atm! :smile:

Let me know if that works!
