### ISSUE TITLE
Autocomplete not showing {listPriceWithTax} & {sellingPriceWithTax}

### ISSUE THREAD

**Issue by doruradu** [vtex-apps/search#82]
Hi!

The autocomplete is not shoing the prices. We had similar issues on the search page, but they were fixed when adding the "__unstableProductOriginVtex" prop. It doesn't seem to work on the autocomplete block. I've added our code bellow. You can test / edit / see in this workspace: https://beta--dacris.myvtex.com/

Thanks!

` "search-bar": {
    "blocks": ["autocomplete-result-list.v2"],
    "props": {
      "openAutocompleteOnFocus": true,
      "placeholder": "Cauta orice, avem atatea solutii ...",
      "displayMode":"clear-button"
    }
  },
  "autocomplete-result-list.v2": {
    "blocks": ["product-summary.shelf#defaultShelf"],
    "props": {
      "__unstableProductOriginVtex": true
    }
  },`

**Comment by chrsmutti** [comment]
Hey @doruradu, were you able to resolve this? Sorry for taking so long!

The configuration should be as follows:

```json
{
  "autocomplete-result-list.v2": {
    "blocks": [
      "product-summary.shelf"
    ],
    "props": {
      "__unstableProductOriginVtex": true
    }
  }
}
```
